### PR TITLE
Travis support

### PR DESCRIPTION
**Pull request by jschueller**
Please enable Travis on the repo prior to merging this.

### CODE REVIEW

**Comment by adumasphi** [comment]
I don't see the project on my travis account. Maybe it's because it is on Felipe account.

**Comment by jschueller** [comment]
maybe you've got to have owner rights.

**Comment by jschueller** [comment]
hey :)

**Comment by felipeam86** [comment]
Sorry for the late response. I enabled Travis for this repo on my Travis account.

We can do the transfer of ownership if you consider it is better

**Comment by jschueller** [comment]
@felipeam86, yes, I think so, I want to be able automatically publish the documentation like the other modules, plus it will be more easily identifiable.

**Comment by felipeam86** [comment]
@jschueller  according to [the docs](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization), to transfer ownership, I need to be admin or have owner permissions on openturns organisation:

> "Users must have admin or owner permissions within the receiving organization before they can transfer a repository that they individually own."

**Comment by jschueller** [comment]
ok, I added you

**Pull request merged**
